from __future__ import annotations

import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import structlog

from sellerclaw_agent.bundle.builder import BundleBuilder
from sellerclaw_agent.bundle.manifest import BundleManifest
from sellerclaw_agent.paths import get_agent_resources_root

_log = structlog.get_logger(__name__)

REJECT_ALREADY_RUNNING = "openclaw_already_running"


def _env_int(key: str, default: str) -> int:
    return int((os.environ.get(key) or default).strip())


_RUNTIME_ENV_FILENAME = "runtime.env"


def _shell_quote_single(value: str) -> str:
    """Quote *value* for safe sourcing from bash (single-quote form)."""
    return "'" + value.replace("'", "'\\''") + "'"


def write_runtime_env(bundle_volume_path: Path, *, proxy_url: str) -> None:
    """Write env file sourced by runtime scripts (``gost_start``, ``openclaw_chrome``).

    Values come from the current manifest so proxy/other per-user settings ride
    through ``POST /manifest`` instead of being baked into machine env.
    """
    bundle_volume_path.mkdir(parents=True, exist_ok=True)
    path = bundle_volume_path / _RUNTIME_ENV_FILENAME
    body = "# Generated by sellerclaw-agent; sourced by runtime scripts.\n"
    body += f"export PROXY_URL={_shell_quote_single((proxy_url or '').strip())}\n"
    tmp = path.with_suffix(".env.tmp")
    tmp.write_text(body, encoding="utf-8")
    os.replace(tmp, path)


def write_bundle_to_disk(
    bundle_volume_path: Path,
    *,
    openclaw_config: str,
    workspaces: dict[str, str],
    proxy_url: str = "",
) -> None:
    root = bundle_volume_path
    oc_dir = root / "openclaw"
    oc_dir.mkdir(parents=True, exist_ok=True)
    (oc_dir / "openclaw.json").write_text(openclaw_config, encoding="utf-8")
    ws_root = root / "workspaces"
    if ws_root.exists():
        shutil.rmtree(ws_root)
    for rel, content in sorted(workspaces.items()):
        path = ws_root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    write_runtime_env(root, proxy_url=proxy_url)


def _first_status_line(stdout: str) -> str:
    text = (stdout or "").strip()
    if not text:
        return ""
    return text.split("\n", 1)[0].strip()


def _parse_pid_from_line(line: str) -> str | None:
    m = re.search(r"\bpid (\d+)\b", line)
    return m.group(1) if m else None


def _parse_uptime_seconds_from_line(line: str) -> float | None:
    # supervisord outputs: "uptime 0:05:07", "uptime 1 day, 2:03:04", "uptime 7 days, 0:05:07"
    m = re.search(
        r"\buptime\s+(?:(\d+)\s+days?,\s*)?(\d+):(\d+)(?::(\d+))?\b",
        line,
        flags=re.IGNORECASE,
    )
    if not m:
        return None
    days_str, g1, g2, g3 = m.group(1), m.group(2), m.group(3), m.group(4)
    try:
        days = int(days_str) if days_str else 0
        a, b = int(g1), int(g2)
    except ValueError:
        return None
    if g3 is not None:
        try:
            c = int(g3)
        except ValueError:
            return None
        return float(days * 86400 + a * 3600 + b * 60 + c)
    return float(days * 86400 + a * 60 + b)


def _classify_supervisor_status_line(line: str) -> tuple[str, str | None]:
    """Map supervisorctl first line to (openclaw_status, openclaw_error) for ping payloads."""
    if not line.strip():
        return "error", "empty supervisorctl status line"

    upper = line.upper()
    if "FATAL" in upper:
        return "error", line
    if "BACKOFF" in upper:
        return "error", line
    if re.search(r"\bSTARTING\b", line):
        return "starting", None
    if re.search(r"\bSTOPPING\b", line):
        return "starting", None
    if re.search(r"\bRUNNING\b", line):
        return "running", None
    if "EXITED" in upper:
        return "stopped", None
    if re.search(r"\bSTOPPED\b", line):
        return "stopped", None
    return "stopped", None


@dataclass
class SupervisorContainerManager:
    """Manage OpenClaw gateway process via supervisord (supervisorctl)."""

    bundle_builder: BundleBuilder
    bundle_volume_path: Path
    display_name: str
    program_name: str
    supervisord_config: str
    gateway_host_port: int
    vnc_host_port: int
    runtime_image_tag: str | None = None

    def _run_ctl(self, *args: str, timeout: float) -> subprocess.CompletedProcess[str]:
        cmd = ["supervisorctl", "-c", self.supervisord_config, *args]
        return subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )

    def _build_bundle(self, manifest: BundleManifest):
        """Build OpenClaw bundle honoring manifest-side model prefix.

        ``model_name_prefix`` is part of the manifest contract and must be threaded
        into ``BundleBuilder.build`` so the rendered ``openclaw.json`` namespaces
        model IDs (``u:<prefix>/complex``/``simple``). Dropping it would produce
        bare model IDs that get rejected by LiteLLM with 401
        ``key not allowed to access model``.
        """
        prefix_raw = (manifest.model_name_prefix or "").strip()
        model_prefix = prefix_raw if prefix_raw else None
        return self.bundle_builder.build(manifest, model_name_prefix=model_prefix)

    def _status_line_raw(self) -> tuple[str, subprocess.CompletedProcess[str]]:
        result = self._run_ctl("status", self.program_name, timeout=5.0)
        line = _first_status_line(result.stdout)
        if line:
            return line, result
        if result.returncode != 0:
            # e.g. cannot connect to supervisord — do not treat stderr as a status line
            return "", result
        line = _first_status_line(result.stderr)
        return line, result

    def probe_openclaw_status(self) -> tuple[str, str | None]:
        try:
            line, result = self._status_line_raw()
            if not line:
                err = (result.stderr or result.stdout or "").strip() or f"supervisorctl exit {result.returncode}"
                return "error", err[:500]
            return _classify_supervisor_status_line(line)
        except Exception as exc:  # noqa: BLE001 - surfaced as probe error
            _log.warning("supervisor_probe_failed", error=str(exc))
            return "error", str(exc)[:500]

    def get_status_detail(self) -> dict[str, Any]:
        port_info = {"gateway": self.gateway_host_port, "vnc": self.vnc_host_port}
        base: dict[str, Any] = {
            "container_name": self.display_name,
            "ports": port_info,
        }
        try:
            line, result = self._status_line_raw()
            if not line:
                err = (result.stderr or result.stdout or "").strip() or f"supervisorctl exit {result.returncode}"
                return {
                    **base,
                    "status": "error",
                    "container_id": None,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": None,
                    "error": err[:500],
                }

            status_norm, probe_err = _classify_supervisor_status_line(line)
            pid = _parse_pid_from_line(line)

            if status_norm == "running":
                return {
                    **base,
                    "status": "running",
                    "container_id": pid,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": _parse_uptime_seconds_from_line(line),
                    "error": None,
                }
            if status_norm == "stopped":
                return {
                    **base,
                    "status": "stopped",
                    "container_id": None,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": None,
                    "error": None,
                }
            if status_norm == "starting":
                return {
                    **base,
                    "status": "starting",
                    "container_id": pid,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": None,
                    "error": None,
                }
            return {
                **base,
                "status": "error",
                "container_id": pid,
                "image": self.runtime_image_tag,
                "uptime_seconds": None,
                "error": probe_err,
            }
        except Exception as exc:  # noqa: BLE001
            _log.warning("supervisor_get_status_detail_failed", error=str(exc))
            return {
                **base,
                "status": "error",
                "container_id": None,
                "image": self.runtime_image_tag,
                "uptime_seconds": None,
                "error": str(exc)[:500],
            }

    def stop(self) -> tuple[str, str | None]:
        try:
            proc = self._run_ctl("stop", self.program_name, timeout=60.0)
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]
        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0:
            return "completed", None
        lowered = out.lower()
        if "not running" in lowered or "no such process" in lowered:
            return "completed", None
        return "failed", out.strip()[:500] or f"exit {proc.returncode}"

    def start(self, manifest: BundleManifest) -> tuple[str, str | None]:
        probe, _ = self.probe_openclaw_status()
        if probe == "running":
            return "rejected", REJECT_ALREADY_RUNNING

        try:
            built = self._build_bundle(manifest)
            write_bundle_to_disk(
                self.bundle_volume_path,
                openclaw_config=built.openclaw_config,
                workspaces=built.workspaces,
                proxy_url=manifest.proxy_url,
            )
        except Exception as exc:  # noqa: BLE001
            _log.warning("bundle_build_write_failed", error=str(exc))
            return "failed", str(exc)[:500]

        try:
            proc = self._run_ctl("start", self.program_name, timeout=60.0)
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]

        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0:
            return "completed", None
        if "already started" in out.lower():
            return "rejected", REJECT_ALREADY_RUNNING
        return "failed", out.strip()[:500] or f"exit {proc.returncode}"

    def restart(self, manifest: BundleManifest) -> tuple[str, str | None]:
        try:
            built = self._build_bundle(manifest)
            write_bundle_to_disk(
                self.bundle_volume_path,
                openclaw_config=built.openclaw_config,
                workspaces=built.workspaces,
                proxy_url=manifest.proxy_url,
            )
        except Exception as exc:  # noqa: BLE001
            _log.warning("bundle_build_write_failed", error=str(exc))
            return "failed", str(exc)[:500]

        try:
            proc = self._run_ctl("restart", self.program_name, timeout=120.0)
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]

        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0:
            return "completed", None
        return "failed", out.strip()[:500] or f"exit {proc.returncode}"


def create_supervisor_manager(
    *,
    bundle_builder: BundleBuilder | None = None,
) -> SupervisorContainerManager:
    """Build manager from environment (used by FastAPI deps and ping loop)."""
    bb = bundle_builder or BundleBuilder(resources_root=get_agent_resources_root())
    raw_image = (os.environ.get("OPENCLAW_RUNTIME_IMAGE") or "").strip()
    return SupervisorContainerManager(
        bundle_builder=bb,
        bundle_volume_path=Path(os.environ.get("OPENCLAW_BUNDLE_VOLUME_PATH", "/opt/config-bundle")),
        display_name=os.environ.get("OPENCLAW_CONTAINER_NAME", "sellerclaw-openclaw"),
        program_name=os.environ.get("OPENCLAW_SUPERVISOR_PROGRAM", "openclaw"),
        supervisord_config=os.environ.get("OPENCLAW_SUPERVISOR_CONF", "/etc/supervisor/conf.d/openclaw.conf"),
        gateway_host_port=_env_int("OPENCLAW_PORT_GATEWAY", "7788"),
        vnc_host_port=_env_int("OPENCLAW_PORT_VNC", "6080"),
        runtime_image_tag=raw_image or None,
    )
