from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import structlog

from sellerclaw_agent.bundle.builder import BundleBuilder
from sellerclaw_agent.bundle.manifest import BundleManifest
from sellerclaw_agent.paths import get_agent_resources_root

_log = structlog.get_logger(__name__)

REJECT_ALREADY_RUNNING = "openclaw_already_running"
REJECT_OPENCLAW_RUNNING_BROWSER = "openclaw_running_browser_command_rejected"


def _env_int(key: str, default: str) -> int:
    return int((os.environ.get(key) or default).strip())


_RUNTIME_ENV_FILENAME = "runtime.env"


def _shell_quote_single(value: str) -> str:
    """Quote *value* for safe sourcing from bash (single-quote form)."""
    return "'" + value.replace("'", "'\\''") + "'"


def write_runtime_env(bundle_volume_path: Path, *, proxy_url: str) -> None:
    """Write env file sourced by runtime scripts (``gost_start``, ``openclaw_chrome``).

    Values come from the current manifest so proxy/other per-user settings ride
    through ``POST /manifest`` instead of being baked into machine env.
    """
    bundle_volume_path.mkdir(parents=True, exist_ok=True)
    path = bundle_volume_path / _RUNTIME_ENV_FILENAME
    body = "# Generated by sellerclaw-agent; sourced by runtime scripts.\n"
    body += f"export PROXY_URL={_shell_quote_single((proxy_url or '').strip())}\n"
    tmp = path.with_suffix(".env.tmp")
    tmp.write_text(body, encoding="utf-8")
    os.replace(tmp, path)


def write_bundle_to_disk(
    bundle_volume_path: Path,
    *,
    openclaw_config: str,
    workspaces: dict[str, str],
    proxy_url: str = "",
) -> None:
    root = bundle_volume_path
    oc_dir = root / "openclaw"
    oc_dir.mkdir(parents=True, exist_ok=True)
    (oc_dir / "openclaw.json").write_text(openclaw_config, encoding="utf-8")
    ws_root = root / "workspaces"
    if ws_root.exists():
        shutil.rmtree(ws_root)
    for rel, content in sorted(workspaces.items()):
        path = ws_root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    write_runtime_env(root, proxy_url=proxy_url)


def _first_status_line(stdout: str) -> str:
    text = (stdout or "").strip()
    if not text:
        return ""
    return text.split("\n", 1)[0].strip()


def _parse_pid_from_line(line: str) -> str | None:
    m = re.search(r"\bpid (\d+)\b", line)
    return m.group(1) if m else None


def _parse_uptime_seconds_from_line(line: str) -> float | None:
    # supervisord outputs: "uptime 0:05:07", "uptime 1 day, 2:03:04", "uptime 7 days, 0:05:07"
    m = re.search(
        r"\buptime\s+(?:(\d+)\s+days?,\s*)?(\d+):(\d+)(?::(\d+))?\b",
        line,
        flags=re.IGNORECASE,
    )
    if not m:
        return None
    days_str, g1, g2, g3 = m.group(1), m.group(2), m.group(3), m.group(4)
    try:
        days = int(days_str) if days_str else 0
        a, b = int(g1), int(g2)
    except ValueError:
        return None
    if g3 is not None:
        try:
            c = int(g3)
        except ValueError:
            return None
        return float(days * 86400 + a * 3600 + b * 60 + c)
    return float(days * 86400 + a * 60 + b)


def _classify_supervisor_status_line(line: str) -> tuple[str, str | None]:
    """Map supervisorctl first line to (openclaw_status, openclaw_error) for ping payloads."""
    if not line.strip():
        return "error", "empty supervisorctl status line"

    upper = line.upper()
    if "FATAL" in upper:
        return "error", line
    if "BACKOFF" in upper:
        return "error", line
    if re.search(r"\bSTARTING\b", line):
        return "starting", None
    if re.search(r"\bSTOPPING\b", line):
        return "starting", None
    if re.search(r"\bRUNNING\b", line):
        return "running", None
    if "EXITED" in upper:
        return "stopped", None
    if re.search(r"\bSTOPPED\b", line):
        return "stopped", None
    return "stopped", None


@dataclass(frozen=True)
class BrowserPageProbe:
    url: str
    title: str
    page_type: str


@dataclass(frozen=True)
class BrowserStatusProbe:
    status: str
    kasmvnc_running: bool
    chrome_running: bool
    error: str | None
    pages: tuple[BrowserPageProbe, ...] | None


@dataclass
class SupervisorContainerManager:
    """Manage OpenClaw gateway process via supervisord (supervisorctl)."""

    bundle_builder: BundleBuilder
    bundle_volume_path: Path
    display_name: str
    program_name: str
    supervisord_config: str
    gateway_host_port: int
    vnc_host_port: int
    runtime_image_tag: str | None = None
    kasm_program_name: str = "kasmvnc"
    gost_program_name: str = "gost"

    def _run_ctl(self, *args: str, timeout: float) -> subprocess.CompletedProcess[str]:
        cmd = ["supervisorctl", "-c", self.supervisord_config, *args]
        return subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )

    def _build_bundle(self, manifest: BundleManifest):
        """Build OpenClaw bundle honoring manifest-side model prefix.

        ``model_name_prefix`` is part of the manifest contract and must be threaded
        into ``BundleBuilder.build`` so the rendered ``openclaw.json`` namespaces
        model IDs (``u:<prefix>/complex``/``simple``). Dropping it would produce
        bare model IDs that get rejected by LiteLLM with 401
        ``key not allowed to access model``.
        """
        prefix_raw = (manifest.model_name_prefix or "").strip()
        model_prefix = prefix_raw if prefix_raw else None
        return self.bundle_builder.build(manifest, model_name_prefix=model_prefix)

    def _status_line_raw(self) -> tuple[str, subprocess.CompletedProcess[str]]:
        result = self._run_ctl("status", self.program_name, timeout=5.0)
        line = _first_status_line(result.stdout)
        if line:
            return line, result
        if result.returncode != 0:
            # e.g. cannot connect to supervisord — do not treat stderr as a status line
            return "", result
        line = _first_status_line(result.stderr)
        return line, result

    def _program_status_line_raw(self, program: str) -> tuple[str, subprocess.CompletedProcess[str]]:
        result = self._run_ctl("status", program, timeout=5.0)
        line = _first_status_line(result.stdout)
        if line:
            return line, result
        if result.returncode != 0:
            return "", result
        line = _first_status_line(result.stderr)
        return line, result

    def _chrome_debug_list_url(self) -> str:
        port = _env_int("OPENCLAW_CHROME_DEBUG_PORT", "7800")
        return f"http://127.0.0.1:{port}/json/list"

    def _fetch_cdp_page_targets(self) -> tuple[list[BrowserPageProbe], str | None]:
        """Return (pages, error). Empty list means CDP reachable but no page targets."""
        url = self._chrome_debug_list_url()
        try:
            with urllib.request.urlopen(url, timeout=1.0) as resp:  # noqa: S310
                raw = resp.read().decode("utf-8", errors="replace")
        except (urllib.error.URLError, TimeoutError, OSError) as exc:
            return [], str(exc)[:500]
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            return [], "invalid CDP json/list"
        if not isinstance(data, list):
            return [], "CDP json/list not a list"
        pages: list[BrowserPageProbe] = []
        for item in data:
            if not isinstance(item, dict):
                continue
            if str(item.get("type") or "") != "page":
                continue
            url_s = str(item.get("url") or "")[:2048]
            title_s = str(item.get("title") or "")[:512]
            if not url_s and not title_s:
                continue
            pages.append(BrowserPageProbe(url=url_s, title=title_s, page_type="page"))
            if len(pages) >= 20:
                break
        return pages, None

    def probe_browser_status(self) -> BrowserStatusProbe:
        """Probe KasmVNC supervisord program and Chrome DevTools /json/list."""
        try:
            line, result = self._program_status_line_raw(self.kasm_program_name)
            if not line:
                err = (result.stderr or result.stdout or "").strip() or f"supervisorctl exit {result.returncode}"
                return BrowserStatusProbe(
                    status="error",
                    kasmvnc_running=False,
                    chrome_running=False,
                    error=err[:500],
                    pages=None,
                )
            kasm_norm, kasm_line_err = _classify_supervisor_status_line(line)
            uptime = _parse_uptime_seconds_from_line(line)

            if kasm_norm in {"error"}:
                return BrowserStatusProbe(
                    status="error",
                    kasmvnc_running=False,
                    chrome_running=False,
                    error=(kasm_line_err or line)[:500],
                    pages=None,
                )
            if kasm_norm == "stopped":
                return BrowserStatusProbe(
                    status="stopped",
                    kasmvnc_running=False,
                    chrome_running=False,
                    error=None,
                    pages=None,
                )
            if kasm_norm == "starting":
                return BrowserStatusProbe(
                    status="starting",
                    kasmvnc_running=True,
                    chrome_running=False,
                    error=None,
                    pages=None,
                )

            pages, cdp_err = self._fetch_cdp_page_targets()
            up = uptime if uptime is not None else 9999.0
            if cdp_err is not None:
                if up < 5.0:
                    return BrowserStatusProbe(
                        status="starting",
                        kasmvnc_running=True,
                        chrome_running=False,
                        error=None,
                        pages=None,
                    )
                return BrowserStatusProbe(
                    status="error",
                    kasmvnc_running=True,
                    chrome_running=False,
                    error=cdp_err,
                    pages=None,
                )
            if pages:
                return BrowserStatusProbe(
                    status="running",
                    kasmvnc_running=True,
                    chrome_running=True,
                    error=None,
                    pages=tuple(pages),
                )
            if up < 5.0:
                return BrowserStatusProbe(
                    status="starting",
                    kasmvnc_running=True,
                    chrome_running=False,
                    error=None,
                    pages=None,
                )
            # CDP responds but no page targets: VNC stack is up; Chrome may be idle or not exposing pages yet.
            return BrowserStatusProbe(
                status="running",
                kasmvnc_running=True,
                chrome_running=False,
                error=None,
                pages=None,
            )
        except Exception as exc:  # noqa: BLE001
            _log.warning("browser_probe_failed", error=str(exc))
            return BrowserStatusProbe(
                status="error",
                kasmvnc_running=False,
                chrome_running=False,
                error=str(exc)[:500],
                pages=None,
            )

    def open_browser(self) -> tuple[str, str | None]:
        """Start KasmVNC sidecars and launch Chrome (dev-admin / remote command)."""
        probe, _ = self.probe_openclaw_status()
        if probe == "running":
            return "rejected", REJECT_OPENCLAW_RUNNING_BROWSER

        try:
            for svc in (self.kasm_program_name, self.gost_program_name):
                proc = self._run_ctl("start", svc, timeout=60.0)
                out = (proc.stdout or "") + (proc.stderr or "")
                if proc.returncode != 0 and "already started" not in out.lower():
                    return "failed", out.strip()[:500] or f"exit {proc.returncode}"
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]

        x11 = Path(os.environ.get("OPENCLAW_BROWSER_X11_SOCKET", "/tmp/.X11-unix/X1"))
        deadline = time.monotonic() + 60.0
        while time.monotonic() < deadline:
            if x11.exists():
                break
            time.sleep(0.2)
        if not x11.exists():
            return "failed", f"X11 display socket not ready: {x11}"

        chrome_bin = os.environ.get("OPENCLAW_CHROME_LAUNCHER", "/usr/local/bin/openclaw_chrome")
        try:
            subprocess.Popen(  # noqa: S603
                [chrome_bin, "about:blank"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                start_new_session=True,
            )
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]
        return "completed", None

    def close_browser(self) -> tuple[str, str | None]:
        """Kill Chrome/Chromium and stop VNC sidecars."""
        pkill_err: str | None = None
        try:
            subprocess.run(  # noqa: S603
                [
                    "/bin/sh",
                    "-c",
                    "pkill -f google-chrome-stable 2>/dev/null || true; "
                    "pkill -f openclaw_chrome 2>/dev/null || true; "
                    "pkill -f '/usr/bin/chromium' 2>/dev/null || true",
                ],
                check=False,
                timeout=30.0,
            )
        except Exception as exc:  # noqa: BLE001
            pkill_err = str(exc)[:500]

        try:
            for svc in (self.kasm_program_name, self.gost_program_name):
                proc = self._run_ctl("stop", svc, timeout=60.0)
                out = (proc.stdout or "") + (proc.stderr or "")
                if proc.returncode != 0:
                    lowered = out.lower()
                    if "not running" not in lowered and "no such process" not in lowered:
                        return "failed", out.strip()[:500] or f"exit {proc.returncode}"
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]

        if pkill_err is not None:
            return "failed", pkill_err
        return "completed", None

    def probe_openclaw_status(self) -> tuple[str, str | None]:
        try:
            line, result = self._status_line_raw()
            if not line:
                err = (result.stderr or result.stdout or "").strip() or f"supervisorctl exit {result.returncode}"
                return "error", err[:500]
            return _classify_supervisor_status_line(line)
        except Exception as exc:  # noqa: BLE001 - surfaced as probe error
            _log.warning("supervisor_probe_failed", error=str(exc))
            return "error", str(exc)[:500]

    def get_status_detail(self) -> dict[str, Any]:
        port_info = {"gateway": self.gateway_host_port, "vnc": self.vnc_host_port}
        base: dict[str, Any] = {
            "container_name": self.display_name,
            "ports": port_info,
        }
        try:
            line, result = self._status_line_raw()
            if not line:
                err = (result.stderr or result.stdout or "").strip() or f"supervisorctl exit {result.returncode}"
                return {
                    **base,
                    "status": "error",
                    "container_id": None,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": None,
                    "error": err[:500],
                }

            status_norm, probe_err = _classify_supervisor_status_line(line)
            pid = _parse_pid_from_line(line)

            if status_norm == "running":
                return {
                    **base,
                    "status": "running",
                    "container_id": pid,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": _parse_uptime_seconds_from_line(line),
                    "error": None,
                }
            if status_norm == "stopped":
                return {
                    **base,
                    "status": "stopped",
                    "container_id": None,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": None,
                    "error": None,
                }
            if status_norm == "starting":
                return {
                    **base,
                    "status": "starting",
                    "container_id": pid,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": None,
                    "error": None,
                }
            return {
                **base,
                "status": "error",
                "container_id": pid,
                "image": self.runtime_image_tag,
                "uptime_seconds": None,
                "error": probe_err,
            }
        except Exception as exc:  # noqa: BLE001
            _log.warning("supervisor_get_status_detail_failed", error=str(exc))
            return {
                **base,
                "status": "error",
                "container_id": None,
                "image": self.runtime_image_tag,
                "uptime_seconds": None,
                "error": str(exc)[:500],
            }

    def stop(self) -> tuple[str, str | None]:
        try:
            proc = self._run_ctl("stop", self.program_name, timeout=60.0)
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]
        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0:
            return "completed", None
        lowered = out.lower()
        if "not running" in lowered or "no such process" in lowered:
            return "completed", None
        return "failed", out.strip()[:500] or f"exit {proc.returncode}"

    def start(self, manifest: BundleManifest) -> tuple[str, str | None]:
        probe, _ = self.probe_openclaw_status()
        if probe == "running":
            return "rejected", REJECT_ALREADY_RUNNING

        try:
            built = self._build_bundle(manifest)
            write_bundle_to_disk(
                self.bundle_volume_path,
                openclaw_config=built.openclaw_config,
                workspaces=built.workspaces,
                proxy_url=manifest.proxy_url,
            )
        except Exception as exc:  # noqa: BLE001
            _log.warning("bundle_build_write_failed", error=str(exc))
            return "failed", str(exc)[:500]

        try:
            proc = self._run_ctl("start", self.program_name, timeout=60.0)
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]

        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0:
            return "completed", None
        if "already started" in out.lower():
            return "rejected", REJECT_ALREADY_RUNNING
        return "failed", out.strip()[:500] or f"exit {proc.returncode}"

    def restart(self, manifest: BundleManifest) -> tuple[str, str | None]:
        try:
            built = self._build_bundle(manifest)
            write_bundle_to_disk(
                self.bundle_volume_path,
                openclaw_config=built.openclaw_config,
                workspaces=built.workspaces,
                proxy_url=manifest.proxy_url,
            )
        except Exception as exc:  # noqa: BLE001
            _log.warning("bundle_build_write_failed", error=str(exc))
            return "failed", str(exc)[:500]

        try:
            proc = self._run_ctl("restart", self.program_name, timeout=120.0)
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]

        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0:
            return "completed", None
        return "failed", out.strip()[:500] or f"exit {proc.returncode}"


def create_supervisor_manager(
    *,
    bundle_builder: BundleBuilder | None = None,
) -> SupervisorContainerManager:
    """Build manager from environment (used by FastAPI deps and ping loop)."""
    bb = bundle_builder or BundleBuilder(resources_root=get_agent_resources_root())
    raw_image = (os.environ.get("OPENCLAW_RUNTIME_IMAGE") or "").strip()
    return SupervisorContainerManager(
        bundle_builder=bb,
        bundle_volume_path=Path(os.environ.get("OPENCLAW_BUNDLE_VOLUME_PATH", "/opt/config-bundle")),
        display_name=os.environ.get("OPENCLAW_CONTAINER_NAME", "sellerclaw-openclaw"),
        program_name=os.environ.get("OPENCLAW_SUPERVISOR_PROGRAM", "openclaw"),
        supervisord_config=os.environ.get("OPENCLAW_SUPERVISOR_CONF", "/etc/supervisor/conf.d/openclaw.conf"),
        gateway_host_port=_env_int("OPENCLAW_PORT_GATEWAY", "7788"),
        vnc_host_port=_env_int("OPENCLAW_PORT_VNC", "6080"),
        runtime_image_tag=raw_image or None,
        kasm_program_name=os.environ.get("OPENCLAW_SUPERVISOR_KASM_PROGRAM", "kasmvnc"),
        gost_program_name=os.environ.get("OPENCLAW_SUPERVISOR_GOST_PROGRAM", "gost"),
    )
