from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import structlog

from sellerclaw_agent.bundle.builder import BundleBuilder
from sellerclaw_agent.bundle.manifest import GenericManifest
from sellerclaw_agent.cloud.state_backup import write_applied_config_version
from sellerclaw_agent.server.secrets_store import get_secrets

_log = structlog.get_logger(__name__)

REJECT_ALREADY_RUNNING = "openclaw_already_running"
REJECT_OPENCLAW_RUNNING_BROWSER = "openclaw_running_browser_command_rejected"


def _env_int(key: str, default: str) -> int:
    return int((os.environ.get(key) or default).strip())


_RUNTIME_ENV_FILENAME = "runtime.env"


def _shell_quote_single(value: str) -> str:
    """Quote *value* for safe sourcing from bash (single-quote form)."""
    return "'" + value.replace("'", "'\\''") + "'"


def write_runtime_env(bundle_volume_path: Path, *, proxy_url: str) -> None:
    """Write env file sourced by runtime scripts (``gost_start``, ``openclaw_chrome``).

    Values come from the current manifest so proxy/other per-user settings ride
    through ``POST /manifest`` instead of being baked into machine env.
    """
    bundle_volume_path.mkdir(parents=True, exist_ok=True)
    path = bundle_volume_path / _RUNTIME_ENV_FILENAME
    body = "# Generated by sellerclaw-agent; sourced by runtime scripts.\n"
    body += f"export PROXY_URL={_shell_quote_single((proxy_url or '').strip())}\n"
    tmp = path.with_suffix(".env.tmp")
    tmp.write_text(body, encoding="utf-8")
    os.replace(tmp, path)


def read_proxy_url_from_runtime_env(bundle_volume_path: Path) -> str | None:
    """Return the ``PROXY_URL`` value currently baked into ``runtime.env``.

    Returns ``None`` when the file does not exist or contains no ``PROXY_URL``
    line — distinguishes "first build" from "proxy explicitly empty" for the
    update-manifest hot-reload guard.
    """
    path = bundle_volume_path / _RUNTIME_ENV_FILENAME
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    except OSError:
        return None
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("export PROXY_URL="):
            continue
        value = stripped.split("=", 1)[1].strip()
        if value.startswith("'") and value.endswith("'") and len(value) >= 2:
            inner = value[1:-1]
            return inner.replace("'\\''", "'")
        if value.startswith('"') and value.endswith('"') and len(value) >= 2:
            return value[1:-1]
        return value
    return None


def _openclaw_config_payload_signature(raw: str) -> object:
    """Parse and normalise ``openclaw.json`` for equality checks.

    ``meta.lastTouchedAt`` is rewritten on every build (the bundle generator
    stamps it with ``datetime.now``), so a naive string compare would always
    mark the on-disk file as stale. Stripping just that field lets us tell
    apart "same config, second debounced apply in a row" from "actual edit".
    """
    payload = json.loads(raw)
    if isinstance(payload, dict):
        meta = payload.get("meta")
        if isinstance(meta, dict) and "lastTouchedAt" in meta:
            meta = {k: v for k, v in meta.items() if k != "lastTouchedAt"}
            payload = {**payload, "meta": meta}
    return payload


def bundle_on_disk_matches(
    bundle_volume_path: Path,
    *,
    openclaw_config: str,
    workspaces: dict[str, str],
    shared_skills: dict[str, str] | None = None,
) -> bool:
    """Return True iff the on-disk bundle is semantically identical to the args.

    Used by ``update_manifest`` to avoid triggering OpenClaw's config file-watcher
    when a debounced apply ran after a no-op edit (e.g. saving the same Telegram
    token twice). False on any read or parse error so we fall through to the
    normal write. Ignores ``meta.lastTouchedAt`` — see
    :func:`_openclaw_config_payload_signature`.
    """
    oc_path = bundle_volume_path / "openclaw" / "openclaw.json"
    try:
        on_disk_raw = oc_path.read_text(encoding="utf-8")
    except (FileNotFoundError, OSError):
        return False
    try:
        if _openclaw_config_payload_signature(
            on_disk_raw
        ) != _openclaw_config_payload_signature(openclaw_config):
            return False
    except (TypeError, ValueError):
        return False

    ws_root = bundle_volume_path / "workspaces"
    existing_ws: dict[str, str] = {}
    if ws_root.exists():
        for path in ws_root.rglob("*"):
            if not path.is_file():
                continue
            try:
                existing_ws[str(path.relative_to(ws_root))] = path.read_text(encoding="utf-8")
            except OSError:
                return False
    if existing_ws != workspaces:
        return False

    shared_root = bundle_volume_path / "shared-skills"
    existing_shared: dict[str, str] = {}
    if shared_root.exists():
        for skill_dir in shared_root.iterdir():
            if not skill_dir.is_dir():
                continue
            skill_path = skill_dir / "SKILL.md"
            if not skill_path.is_file():
                continue
            try:
                existing_shared[skill_dir.name] = skill_path.read_text(encoding="utf-8")
            except OSError:
                return False
    return existing_shared == (shared_skills or {})


def write_bundle_to_disk(
    bundle_volume_path: Path,
    *,
    openclaw_config: str,
    workspaces: dict[str, str],
    shared_skills: dict[str, str] | None = None,
    proxy_url: str = "",
) -> None:
    root = bundle_volume_path
    oc_dir = root / "openclaw"
    oc_dir.mkdir(parents=True, exist_ok=True)
    (oc_dir / "openclaw.json").write_text(openclaw_config, encoding="utf-8")
    ws_root = root / "workspaces"
    if ws_root.exists():
        shutil.rmtree(ws_root)
    for rel, content in sorted(workspaces.items()):
        path = ws_root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    # Optional top-level shared-skills (usually empty; skills live under each workspace).
    shared_root = root / "shared-skills"
    if shared_root.exists():
        shutil.rmtree(shared_root)
    for skill_name, content in sorted((shared_skills or {}).items()):
        skill_path = shared_root / skill_name / "SKILL.md"
        skill_path.parent.mkdir(parents=True, exist_ok=True)
        skill_path.write_text(content, encoding="utf-8")
    write_runtime_env(root, proxy_url=proxy_url)


def _first_status_line(stdout: str) -> str:
    text = (stdout or "").strip()
    if not text:
        return ""
    return text.split("\n", 1)[0].strip()


def _parse_pid_from_line(line: str) -> str | None:
    m = re.search(r"\bpid (\d+)\b", line)
    return m.group(1) if m else None


def _parse_uptime_seconds_from_line(line: str) -> float | None:
    # supervisord outputs: "uptime 0:05:07", "uptime 1 day, 2:03:04", "uptime 7 days, 0:05:07"
    m = re.search(
        r"\buptime\s+(?:(\d+)\s+days?,\s*)?(\d+):(\d+)(?::(\d+))?\b",
        line,
        flags=re.IGNORECASE,
    )
    if not m:
        return None
    days_str, g1, g2, g3 = m.group(1), m.group(2), m.group(3), m.group(4)
    try:
        days = int(days_str) if days_str else 0
        a, b = int(g1), int(g2)
    except ValueError:
        return None
    if g3 is not None:
        try:
            c = int(g3)
        except ValueError:
            return None
        return float(days * 86400 + a * 3600 + b * 60 + c)
    return float(days * 86400 + a * 60 + b)


def _is_ready_payload(body: str) -> bool:
    """Return True iff gateway ``/ready`` body is JSON with ``ready: true``."""
    try:
        payload = json.loads(body)
    except (ValueError, TypeError):
        return False
    return isinstance(payload, dict) and payload.get("ready") is True


def _classify_supervisor_status_line(line: str) -> tuple[str, str | None]:
    """Map supervisorctl first line to (openclaw_status, openclaw_error) for ping payloads."""
    if not line.strip():
        return "error", "empty supervisorctl status line"

    upper = line.upper()
    if "FATAL" in upper:
        return "error", line
    if "BACKOFF" in upper:
        return "error", line
    if re.search(r"\bSTARTING\b", line):
        return "starting", None
    if re.search(r"\bSTOPPING\b", line):
        return "starting", None
    if re.search(r"\bRUNNING\b", line):
        return "running", None
    if "EXITED" in upper:
        return "stopped", None
    if re.search(r"\bSTOPPED\b", line):
        return "stopped", None
    return "stopped", None


@dataclass(frozen=True)
class BrowserPageProbe:
    url: str
    title: str
    page_type: str


@dataclass(frozen=True)
class BrowserStatusProbe:
    status: str
    kasmvnc_running: bool
    chrome_running: bool
    error: str | None
    pages: tuple[BrowserPageProbe, ...] | None


@dataclass
class SupervisorContainerManager:
    """Manage OpenClaw gateway process via supervisord (supervisorctl)."""

    bundle_builder: BundleBuilder
    bundle_volume_path: Path
    display_name: str
    program_name: str
    supervisord_config: str
    gateway_host_port: int
    vnc_host_port: int
    runtime_image_tag: str | None = None
    kasm_program_name: str = "kasmvnc"
    gost_program_name: str = "gost"
    credentials_data_dir: Path | None = None
    openclaw_start_cmd: str = "/usr/local/bin/openclaw_start"

    def _run_ctl(self, *args: str, timeout: float) -> subprocess.CompletedProcess[str]:
        cmd = ["supervisorctl", "-c", self.supervisord_config, *args]
        return subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )

    def _apply_bundle(self, *, timeout: float = 60.0) -> subprocess.CompletedProcess[str]:
        """Activate the freshly written bundle into the live config + workspaces.

        Runs ``openclaw_start apply-bundle`` (same user as the gateway): it copies the
        staged ``/opt/config-bundle`` into the locations OpenClaw actually reads
        (``/opt/openclaw-config``, ``/opt/openclaw-workspaces`` and ``~/.openclaw``) so
        the config file-watcher reloads ``openclaw.json`` and new sessions pick up the
        updated workspace ``AGENTS.md`` — without bouncing the gateway. Does NOT
        re-fetch the bundle; it is already on disk from :func:`write_bundle_to_disk`.
        """
        return subprocess.run(
            [self.openclaw_start_cmd, "apply-bundle"],
            capture_output=True,
            text=True,
            timeout=timeout,
        )

    def _build_bundle(self, manifest: GenericManifest):
        """Build the OpenClaw bundle from the generic manifest.

        The LiteLLM ``model_name_prefix`` now lives inside the manifest's litellm
        group, so ``BundleBuilder.build`` derives it directly — no need to thread it
        through here. It namespaces model IDs (``u:<prefix>/complex``/``simple``);
        bare model IDs would get rejected by LiteLLM with 401
        ``key not allowed to access model``.
        """
        if self.credentials_data_dir is None:
            raise ValueError("credentials_data_dir is required to build OpenClaw bundles")
        sec = get_secrets(self.credentials_data_dir)
        return self.bundle_builder.build(
            manifest,
            gateway_token=sec.gateway_token,
            hooks_token=sec.hooks_token,
            data_dir=self.credentials_data_dir,
        )

    def _status_line_raw(self) -> tuple[str, subprocess.CompletedProcess[str]]:
        result = self._run_ctl("status", self.program_name, timeout=5.0)
        line = _first_status_line(result.stdout)
        if line:
            return line, result
        if result.returncode != 0:
            # e.g. cannot connect to supervisord — do not treat stderr as a status line
            return "", result
        line = _first_status_line(result.stderr)
        return line, result

    def _program_status_line_raw(self, program: str) -> tuple[str, subprocess.CompletedProcess[str]]:
        result = self._run_ctl("status", program, timeout=5.0)
        line = _first_status_line(result.stdout)
        if line:
            return line, result
        if result.returncode != 0:
            return "", result
        line = _first_status_line(result.stderr)
        return line, result

    def _chrome_debug_list_url(self) -> str:
        port = _env_int("OPENCLAW_CHROME_DEBUG_PORT", "7800")
        return f"http://127.0.0.1:{port}/json/list"

    def _fetch_cdp_page_targets(self) -> tuple[list[BrowserPageProbe], str | None]:
        """Return (pages, error). Empty list means CDP reachable but no page targets."""
        url = self._chrome_debug_list_url()
        try:
            with urllib.request.urlopen(url, timeout=1.0) as resp:  # noqa: S310
                raw = resp.read().decode("utf-8", errors="replace")
        except (urllib.error.URLError, TimeoutError, OSError) as exc:
            return [], str(exc)[:500]
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            return [], "invalid CDP json/list"
        if not isinstance(data, list):
            return [], "CDP json/list not a list"
        pages: list[BrowserPageProbe] = []
        for item in data:
            if not isinstance(item, dict):
                continue
            if str(item.get("type") or "") != "page":
                continue
            url_s = str(item.get("url") or "")[:2048]
            title_s = str(item.get("title") or "")[:512]
            if not url_s and not title_s:
                continue
            pages.append(BrowserPageProbe(url=url_s, title=title_s, page_type="page"))
            if len(pages) >= 20:
                break
        return pages, None

    def probe_browser_status(self) -> BrowserStatusProbe:
        """Probe KasmVNC supervisord program and Chrome DevTools /json/list."""
        try:
            line, result = self._program_status_line_raw(self.kasm_program_name)
            if not line:
                err = (result.stderr or result.stdout or "").strip() or f"supervisorctl exit {result.returncode}"
                return BrowserStatusProbe(
                    status="error",
                    kasmvnc_running=False,
                    chrome_running=False,
                    error=err[:500],
                    pages=None,
                )
            kasm_norm, kasm_line_err = _classify_supervisor_status_line(line)
            uptime = _parse_uptime_seconds_from_line(line)

            if kasm_norm in {"error"}:
                return BrowserStatusProbe(
                    status="error",
                    kasmvnc_running=False,
                    chrome_running=False,
                    error=(kasm_line_err or line)[:500],
                    pages=None,
                )
            if kasm_norm == "stopped":
                return BrowserStatusProbe(
                    status="stopped",
                    kasmvnc_running=False,
                    chrome_running=False,
                    error=None,
                    pages=None,
                )
            if kasm_norm == "starting":
                return BrowserStatusProbe(
                    status="starting",
                    kasmvnc_running=True,
                    chrome_running=False,
                    error=None,
                    pages=None,
                )

            pages, cdp_err = self._fetch_cdp_page_targets()
            up = uptime if uptime is not None else 9999.0
            if cdp_err is not None:
                if up < 5.0:
                    return BrowserStatusProbe(
                        status="starting",
                        kasmvnc_running=True,
                        chrome_running=False,
                        error=None,
                        pages=None,
                    )
                return BrowserStatusProbe(
                    status="error",
                    kasmvnc_running=True,
                    chrome_running=False,
                    error=cdp_err,
                    pages=None,
                )
            if pages:
                return BrowserStatusProbe(
                    status="running",
                    kasmvnc_running=True,
                    chrome_running=True,
                    error=None,
                    pages=tuple(pages),
                )
            if up < 5.0:
                return BrowserStatusProbe(
                    status="starting",
                    kasmvnc_running=True,
                    chrome_running=False,
                    error=None,
                    pages=None,
                )
            # CDP responds but no page targets: VNC stack is up; Chrome may be idle or not exposing pages yet.
            return BrowserStatusProbe(
                status="running",
                kasmvnc_running=True,
                chrome_running=False,
                error=None,
                pages=None,
            )
        except Exception as exc:  # noqa: BLE001
            _log.warning("browser_probe_failed", error=str(exc))
            return BrowserStatusProbe(
                status="error",
                kasmvnc_running=False,
                chrome_running=False,
                error=str(exc)[:500],
                pages=None,
            )

    def open_browser(self) -> tuple[str, str | None]:
        """Start KasmVNC sidecars and launch Chrome (dev-admin / remote command)."""
        probe, _ = self.probe_openclaw_status()
        if probe == "running":
            return "rejected", REJECT_OPENCLAW_RUNNING_BROWSER

        try:
            for svc in (self.kasm_program_name, self.gost_program_name):
                proc = self._run_ctl("start", svc, timeout=60.0)
                out = (proc.stdout or "") + (proc.stderr or "")
                if proc.returncode != 0 and "already started" not in out.lower():
                    return "failed", out.strip()[:500] or f"exit {proc.returncode}"
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]

        x11 = Path(os.environ.get("OPENCLAW_BROWSER_X11_SOCKET", "/tmp/.X11-unix/X1"))
        deadline = time.monotonic() + 60.0
        while time.monotonic() < deadline:
            if x11.exists():
                break
            time.sleep(0.2)
        if not x11.exists():
            return "failed", f"X11 display socket not ready: {x11}"

        chrome_bin = os.environ.get("OPENCLAW_CHROME_LAUNCHER", "/usr/local/bin/openclaw_chrome")
        try:
            subprocess.Popen(  # noqa: S603
                [chrome_bin, "about:blank"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                start_new_session=True,
            )
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]
        return "completed", None

    def _browser_display(self) -> str:
        """X display the VNC/browser stack runs on (e.g. ``:1``)."""
        return (os.environ.get("OPENCLAW_BROWSER_DISPLAY") or ":1").strip() or ":1"

    def _browser_profile_dir(self) -> str:
        """Chrome ``user-data`` dir the OpenClaw browser plugin manages."""
        home = (os.environ.get("HOME") or "/home/node").rstrip("/")
        default = f"{home}/.openclaw/browser/openclaw/user-data"
        return (os.environ.get("OPENCLAW_BROWSER_PROFILE_DIR") or default).strip() or default

    def _cleanup_browser_runtime(self) -> str | None:
        """Kill Chrome + the (possibly orphaned) Xvnc and clear stale locks.

        ``supervisorctl stop kasmvnc`` only signals the ``vncserver`` wrapper;
        the ``Xvnc`` server it spawned runs in its own session and survives as
        an orphan, still holding display ``:N`` via its abstract socket
        (``@/tmp/.X11-unix/XN``). That is why a reopen later fails with
        "Cannot establish any listening sockets / server already running": the
        new Xvnc can't claim the display, the filesystem socket is never
        recreated, and the Chrome launcher waits forever for it. So we kill the
        orphaned Xvnc explicitly and drop the stale display + Chrome singleton
        locks (the latter left behind whenever Chrome is ``pkill``ed rather than
        quit cleanly) so the next ``open_browser`` starts from a clean slate.

        Returns an error string on failure, else ``None``.
        """
        display = self._browser_display()
        disp_num = display.lstrip(":") or "1"
        profile = _shell_quote_single(self._browser_profile_dir())
        # ``pkill -f`` matches full command lines, including this very script's
        # command line — so a naive ``pkill -f Xvnc`` kills the shell running it
        # before the later cleanup steps run. The ``[X]`` bracket trick makes
        # the regex match the real process while NOT matching the literal
        # ``[X]vnc`` text inside this script.
        script = (
            # Close Chrome (launched outside supervisor by openclaw_chrome).
            "pkill -f '[g]oogle-chrome-stable' 2>/dev/null || true; "
            "pkill -f '[o]penclaw_chrome' 2>/dev/null || true; "
            "pkill -f '[/]usr/bin/chromium' 2>/dev/null || true; "
            # Kill the X server that outlives `supervisorctl stop kasmvnc`.
            f"pkill -f '[X]vnc {display} ' 2>/dev/null || true; "
            f"pkill -f '[v]ncserver {display} ' 2>/dev/null || true; "
            # Drop stale display + Chrome singleton locks so a reopen starts clean.
            f"rm -f /tmp/.X11-unix/X{disp_num} /tmp/.X{disp_num}-lock 2>/dev/null || true; "
            f"rm -f {profile}/Singleton* 2>/dev/null || true"
        )
        try:
            subprocess.run(  # noqa: S603
                ["/bin/sh", "-c", script],
                check=False,
                timeout=30.0,
            )
        except Exception as exc:  # noqa: BLE001
            return str(exc)[:500]
        return None

    def close_browser(self) -> tuple[str, str | None]:
        """Close Chrome and fully tear down the VNC display so it can reopen.

        Order matters: stop the supervised ``vncserver`` wrapper first (an
        explicit stop disables supervisord's autorestart), then kill the
        now-orphaned ``Xvnc`` and clear locks. Cleanup runs even when the
        supervisor stop fails, so Chrome/orphans never linger.
        """
        stop_err: str | None = None
        try:
            for svc in (self.kasm_program_name, self.gost_program_name):
                proc = self._run_ctl("stop", svc, timeout=60.0)
                out = (proc.stdout or "") + (proc.stderr or "")
                if proc.returncode != 0:
                    lowered = out.lower()
                    if "not running" not in lowered and "no such process" not in lowered:
                        stop_err = out.strip()[:500] or f"exit {proc.returncode}"
                        break
        except Exception as exc:  # noqa: BLE001
            stop_err = str(exc)[:500]

        cleanup_err = self._cleanup_browser_runtime()

        if stop_err is not None:
            return "failed", stop_err
        if cleanup_err is not None:
            return "failed", cleanup_err
        return "completed", None

    def _gateway_ready_url(self) -> str:
        return f"http://127.0.0.1:{self.gateway_host_port}/ready"

    def _gateway_is_ready(self, *, timeout: float = 1.5) -> bool:
        """Return True iff gateway ``/ready`` responded 200 with ``ready: true``.

        Supervisor reports RUNNING as soon as the openclaw process stays up for
        >startsecs, but the gateway HTTP listener (and plugin registry) can take
        tens of seconds more to come up. Probing ``/ready`` lets us distinguish
        "process alive" from "accepting inbound traffic" — otherwise the cloud
        forwards user chat messages that immediately drop with ConnectError on
        the local POST /channels/sellerclaw-ui/inbound.
        """
        url = self._gateway_ready_url()
        try:
            with urllib.request.urlopen(url, timeout=timeout) as resp:  # noqa: S310
                if not (200 <= resp.status < 300):
                    return False
                raw = resp.read()
        except (urllib.error.URLError, TimeoutError, OSError):
            return False
        body = raw.decode("utf-8", "replace") if isinstance(raw, (bytes, bytearray)) else str(raw)
        return _is_ready_payload(body)

    def probe_openclaw_status(self) -> tuple[str, str | None]:
        try:
            line, result = self._status_line_raw()
            if not line:
                err = (result.stderr or result.stdout or "").strip() or f"supervisorctl exit {result.returncode}"
                return "error", err[:500]
            status, err = _classify_supervisor_status_line(line)
            if status == "running" and not self._gateway_is_ready():
                return "starting", None
            return status, err
        except Exception as exc:  # noqa: BLE001 - surfaced as probe error
            _log.warning("supervisor_probe_failed", error=str(exc))
            return "error", str(exc)[:500]

    def get_status_detail(self) -> dict[str, Any]:
        port_info = {"gateway": self.gateway_host_port, "vnc": self.vnc_host_port}
        base: dict[str, Any] = {
            "container_name": self.display_name,
            "ports": port_info,
        }
        try:
            line, result = self._status_line_raw()
            if not line:
                err = (result.stderr or result.stdout or "").strip() or f"supervisorctl exit {result.returncode}"
                return {
                    **base,
                    "status": "error",
                    "container_id": None,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": None,
                    "error": err[:500],
                }

            status_norm, probe_err = _classify_supervisor_status_line(line)
            pid = _parse_pid_from_line(line)

            if status_norm == "running":
                return {
                    **base,
                    "status": "running",
                    "container_id": pid,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": _parse_uptime_seconds_from_line(line),
                    "error": None,
                }
            if status_norm == "stopped":
                return {
                    **base,
                    "status": "stopped",
                    "container_id": None,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": None,
                    "error": None,
                }
            if status_norm == "starting":
                return {
                    **base,
                    "status": "starting",
                    "container_id": pid,
                    "image": self.runtime_image_tag,
                    "uptime_seconds": None,
                    "error": None,
                }
            return {
                **base,
                "status": "error",
                "container_id": pid,
                "image": self.runtime_image_tag,
                "uptime_seconds": None,
                "error": probe_err,
            }
        except Exception as exc:  # noqa: BLE001
            _log.warning("supervisor_get_status_detail_failed", error=str(exc))
            return {
                **base,
                "status": "error",
                "container_id": None,
                "image": self.runtime_image_tag,
                "uptime_seconds": None,
                "error": str(exc)[:500],
            }

    def stop(self) -> tuple[str, str | None]:
        try:
            proc = self._run_ctl("stop", self.program_name, timeout=60.0)
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]
        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0:
            return "completed", None
        lowered = out.lower()
        if "not running" in lowered or "no such process" in lowered:
            return "completed", None
        return "failed", out.strip()[:500] or f"exit {proc.returncode}"

    def start(self, manifest: GenericManifest) -> tuple[str, str | None]:
        probe, _ = self.probe_openclaw_status()
        if probe == "running":
            return "rejected", REJECT_ALREADY_RUNNING

        try:
            built = self._build_bundle(manifest)
            write_bundle_to_disk(
                self.bundle_volume_path,
                openclaw_config=built.openclaw_config,
                workspaces=built.workspaces,
                shared_skills=built.shared_skills,
                proxy_url=manifest.proxy_url,
            )
        except Exception as exc:  # noqa: BLE001
            _log.warning("bundle_build_write_failed", error=str(exc))
            return "failed", str(exc)[:500]

        try:
            proc = self._run_ctl("start", self.program_name, timeout=60.0)
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]

        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0:
            write_applied_config_version(manifest.config_version)
            return "completed", None
        if "already started" in out.lower():
            return "rejected", REJECT_ALREADY_RUNNING
        return "failed", out.strip()[:500] or f"exit {proc.returncode}"

    def restart(self, manifest: GenericManifest) -> tuple[str, str | None]:
        try:
            built = self._build_bundle(manifest)
            write_bundle_to_disk(
                self.bundle_volume_path,
                openclaw_config=built.openclaw_config,
                workspaces=built.workspaces,
                shared_skills=built.shared_skills,
                proxy_url=manifest.proxy_url,
            )
        except Exception as exc:  # noqa: BLE001
            _log.warning("bundle_build_write_failed", error=str(exc))
            return "failed", str(exc)[:500]

        try:
            proc = self._run_ctl("restart", self.program_name, timeout=120.0)
        except Exception as exc:  # noqa: BLE001
            return "failed", str(exc)[:500]

        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0:
            write_applied_config_version(manifest.config_version)
            return "completed", None
        return "failed", out.strip()[:500] or f"exit {proc.returncode}"

    def update_manifest(self, manifest: GenericManifest) -> tuple[str, str | None]:
        """Rebuild + activate the bundle on disk without bouncing the gateway process.

        Writing the bundle alone is not enough: it lands in the staging volume
        (``/opt/config-bundle``), but OpenClaw reads its config and workspaces from
        ``~/.openclaw`` (materialised from the staging bundle only at process start).
        So after writing we run ``openclaw_start apply-bundle`` to copy the staging
        bundle into the live locations. OpenClaw's file-watcher
        (``gateway.reload.mode=hybrid`` by default) then picks up the refreshed
        ``openclaw.json`` — channels, tool allow-lists, mcp config, cron and the
        subagent roster (``allowAgents``) hot-apply in place. Workspaces land on disk
        too, but the running session keeps its already-injected ``AGENTS.md`` /
        ``SOUL.md``; only new sessions see the updated content. That's why bucket-3
        changes (e.g. enabling/removing a specialist) carry a separate "Start a new
        chat" hint on the cloud side.

        Two early returns guard against silently doing the wrong thing:

        * **Proxy change** — ``proxy_url`` lives in ``runtime.env`` and is read
          by supervisord at process start. A hot-reload can't apply it; the
          cloud classifier should never route a proxy change here, but reject
          loudly if the contract slips.
        * **No-op** — same byte content as on disk. Skipping the write avoids
          waking the file-watcher for nothing (it would re-validate the config
          and emit a noise log line on every duplicate save).
        """
        current_proxy = read_proxy_url_from_runtime_env(self.bundle_volume_path)
        new_proxy = (manifest.proxy_url or "").strip()
        if (current_proxy or "") != new_proxy:
            return (
                "failed",
                "proxy change requires a full restart (PROXY_URL is read by supervisord only at start)",
            )
        try:
            built = self._build_bundle(manifest)
        except Exception as exc:  # noqa: BLE001
            _log.warning("bundle_build_failed", error=str(exc))
            return "failed", str(exc)[:500]
        if bundle_on_disk_matches(
            self.bundle_volume_path,
            openclaw_config=built.openclaw_config,
            workspaces=built.workspaces,
            shared_skills=built.shared_skills,
        ):
            _log.info("update_manifest_noop", reason="bundle_unchanged")
            # Bundle byte-identical, but the cloud may have bumped config_version (a change
            # that doesn't alter the rendered bundle). Record it so the reported applied
            # version still advances — otherwise the cloud would re-push forever.
            write_applied_config_version(manifest.config_version)
            return "completed", None
        try:
            write_bundle_to_disk(
                self.bundle_volume_path,
                openclaw_config=built.openclaw_config,
                workspaces=built.workspaces,
                shared_skills=built.shared_skills,
                proxy_url=manifest.proxy_url,
            )
        except Exception as exc:  # noqa: BLE001
            _log.warning("bundle_write_failed", error=str(exc))
            return "failed", str(exc)[:500]
        # Activate the staged bundle into the live config/workspaces so the change
        # actually reaches the running gateway (see method docstring). Without this the
        # write only pre-stages for the next start/restart and the hot-reload is a no-op.
        try:
            proc = self._apply_bundle()
        except Exception as exc:  # noqa: BLE001
            _log.warning("apply_bundle_failed", error=str(exc))
            return "failed", str(exc)[:500]
        if proc.returncode != 0:
            out = ((proc.stderr or "") + (proc.stdout or "")).strip()
            _log.warning("apply_bundle_nonzero", returncode=proc.returncode, output=out[:500])
            return "failed", out[:500] or f"apply-bundle exit {proc.returncode}"
        write_applied_config_version(manifest.config_version)
        return "completed", None


def create_supervisor_manager(
    *,
    bundle_builder: BundleBuilder | None = None,
) -> SupervisorContainerManager:
    """Build manager from environment (used by FastAPI deps and ping loop)."""
    bb = bundle_builder or BundleBuilder()
    raw_image = (os.environ.get("OPENCLAW_RUNTIME_IMAGE") or "").strip()
    data_dir = Path(os.environ.get("SELLERCLAW_DATA_DIR", "/data"))
    return SupervisorContainerManager(
        bundle_builder=bb,
        bundle_volume_path=Path(os.environ.get("OPENCLAW_BUNDLE_VOLUME_PATH", "/opt/config-bundle")),
        display_name=os.environ.get("OPENCLAW_CONTAINER_NAME", "sellerclaw-openclaw"),
        program_name=os.environ.get("OPENCLAW_SUPERVISOR_PROGRAM", "openclaw"),
        supervisord_config=os.environ.get("OPENCLAW_SUPERVISOR_CONF", "/etc/supervisor/conf.d/openclaw.conf"),
        gateway_host_port=_env_int("OPENCLAW_PORT_GATEWAY", "7788"),
        vnc_host_port=_env_int("OPENCLAW_PORT_VNC", "6080"),
        runtime_image_tag=raw_image or None,
        kasm_program_name=os.environ.get("OPENCLAW_SUPERVISOR_KASM_PROGRAM", "kasmvnc"),
        gost_program_name=os.environ.get("OPENCLAW_SUPERVISOR_GOST_PROGRAM", "gost"),
        credentials_data_dir=data_dir,
        openclaw_start_cmd=os.environ.get("OPENCLAW_START_CMD", "/usr/local/bin/openclaw_start"),
    )
